---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: kite-vm
    box: Bassualdo/rpd-amd64-buster
    instance_raw_config_args:
      - "ssh.username = 'pi'"
      - "ssh.password = 'raspberry'"
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    options:
      x:
        - 301
        - 306  # ignore pipefail for pipes. Testing
        - 503  # task when changed allowed no handler needed
scenario:
  name: integration
verifier:
  name: testinfra
  lint:
    name: flake8
