---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: instance
    image: ${MOLECULE_DISTRO:-debian:10}
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    options:
      x:
        - 301
        - 306  # ignore pipefail for pipes. Testing
        - 503  # task when changed allowed no handler needed
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
